### ISSUE TITLE
User UI Mockup and Storyboard

### ISSUE THREAD

**Issue by alimbaga** [cmput301w19t06/TheUndesirableJackals#3]
### Eclass Instructions:
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, provide storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.

**Comment by r3nz00** [comment]
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request

**Comment by alimbaga** [comment]
**Checklist**

Please check the box if you are working on the specified section

- [x] Login Activity
- [x] Main Home View
- [x] Additional Menu
- [x] Adding And Deleting books in My books
- [x] Searching
- [x] Requesting Books
- [x] Returning Books
- [x] Messaging Users
