### ISSUE TITLE
Release Planning Ambiguous

### ISSUE THREAD

**Issue by alimbaga** [cmput301w19t06/TheUndesirableJackals#8]
**Mentor's comment:** 
Release planning ambiguous.Add information to release planning. What test cases need to be written for each user story. What back-end (coding, wireframing) and front-end (UI) effort is required. Abstractly define how the responsibility will be divided. Provide dates weekly/monthly of when to complete what. You can reason about groups of user stories in this regard.

**Comment by ghost** [comment]
I changed the layout of the release planning to make it less ambiguous. I also organized the requirements in small groups and added back-end/front-end efforts and potential test cases that we need to write for each group.

Division of responsibilities need to be writen as well.
